# Default values for ctfd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

mariadb:
  enabled: true
  replication:
    enabled: false

  db:
    name: ctfd
    user: ctfd
    password: ctfd

  rootUser:
    password: ctfd

redis:
  usePassword: false
  cluster:
    enabled: false
