apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "ctfd.fullname" . }}-uploads-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
